name: build_and_push_docker.yml

on:
  push:
    branches:
      - main
    tags:
      - 'v0.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ['ACC', 'NOT_ACC']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Container Registry
        uses: docker/login-action@1cce1654e01caa87cc0eac1c100e6749708affb9
        with:
          registry: "docker.gitlab.gwdg.de"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        with:
          push: true
          file: ${{ matrix.dockerfile }}
          tags: docker.gitlab.gwdg.de/dfg/ui:${{ matrix.dockerfile }}-latest
