name: build_and_push_docker.yml

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ['ACC', 'NOT_ACC']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: "docker.gitlab.gwdg.de"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          file: ${{ matrix.dockerfile }}
          tags: docker.gitlab.gwdg.de/dfg/ui:${{ matrix.dockerfile }}-latest
